apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-microproject-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/k8s-microproject-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-microproject-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi